# Generated by Django 2.0.5 on 2018-05-21 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_mustbuy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mustbuy',
            new_name='Topmustbuy',
        ),
    ]
