# Generated by Django 2.0.5 on 2018-05-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_topshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshop',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
