# Generated by Django 2.0.5 on 2018-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_topshop_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMainShow',
            fields=[
                ('trackid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('categoryid', models.CharField(max_length=10)),
                ('brandname', models.CharField(max_length=20)),
                ('img1', models.CharField(max_length=300)),
                ('childcid1', models.CharField(max_length=20)),
                ('productid1', models.CharField(max_length=30)),
                ('longname1', models.CharField(max_length=50)),
                ('price1', models.CharField(max_length=10)),
                ('marketprice1', models.CharField(max_length=10)),
                ('img2', models.CharField(max_length=300)),
                ('childcid2', models.CharField(max_length=20)),
                ('productid2', models.CharField(max_length=30)),
                ('longname2', models.CharField(max_length=50)),
                ('price2', models.CharField(max_length=10)),
                ('marketprice2', models.CharField(max_length=10)),
                ('img3', models.CharField(max_length=300)),
                ('childcid3', models.CharField(max_length=20)),
                ('productid3', models.CharField(max_length=30)),
                ('longname3', models.CharField(max_length=50)),
                ('price3', models.CharField(max_length=10)),
                ('marketprice3', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
