# Generated by Django 2.0.5 on 2018-05-21 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_topmainshow'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topmainshow',
            table='axf_mainshow',
        ),
    ]
