# Generated by Django 2.0.5 on 2018-05-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20180521_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMainChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=300)),
                ('childcid', models.CharField(max_length=20)),
                ('productid', models.CharField(max_length=30)),
                ('longname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('marketprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_mainchild',
            },
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='childcid1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='childcid2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='childcid3',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='longname1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='longname2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='longname3',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='marketprice1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='marketprice2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='marketprice3',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='productid1',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='productid2',
        ),
        migrations.RemoveField(
            model_name='topmainshow',
            name='productid3',
        ),
        migrations.AddField(
            model_name='topmainchild',
            name='topMainShow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.TopMainShow'),
        ),
    ]
