# Generated by Django 2.0.5 on 2018-05-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20180522_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernumber', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('userpasswd', models.CharField(max_length=20)),
                ('userphone', models.CharField(max_length=11)),
                ('useraaddress', models.CharField(max_length=100)),
                ('userphoto', models.ImageField(upload_to='userphoto')),
                ('token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
    ]
