# Generated by Django 2.0.5 on 2018-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20180525_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
