# Generated by Django 2.0.5 on 2018-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_deliveryaddress_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='only',
            field=models.IntegerField(default=0),
        ),
    ]
